# Generated by Django 2.2.7 on 2020-06-29 02:04

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('contenido', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='contenido')),
                ('slug', models.CharField(default='---', max_length=128, unique=True)),
                ('ruta_imagen', models.FileField(blank=True, null=True, upload_to='videos/%Y/%m/%d')),
                ('titulo', models.CharField(default='---', max_length=200)),
                ('resumen', models.CharField(default='---', max_length=200)),
            ],
        ),
    ]
