# Generated by Django 2.2.7 on 2020-06-22 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simulacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitud', models.FloatField()),
                ('Longitud', models.FloatField()),
                ('fecha_publicacion', models.DateTimeField(verbose_name='Fecha de publicacion')),
            ],
        ),
    ]
