# Generated by Django 2.2.7 on 2020-06-22 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulacion',
            name='Resultado',
            field=models.FloatField(default=0, verbose_name='Power'),
        ),
        migrations.AlterField(
            model_name='simulacion',
            name='Latitud',
            field=models.FloatField(verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='simulacion',
            name='Longitud',
            field=models.FloatField(verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='simulacion',
            name='fecha_publicacion',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date'),
        ),
    ]
