# Generated by Django 2.2.7 on 2020-06-23 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200622_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulacion',
            name='ruta_imagen',
            field=models.FileField(blank=True, default='<built-in function id>.png', null=True, upload_to='simulaciones/%Y/%m/%d'),
        ),
    ]
