# Generated by Django 2.2.7 on 2020-06-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_simulacion_ruta_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulacion',
            name='ruta_imagen',
            field=models.FileField(blank=True, default='fig.png', null=True, upload_to='simulaciones/%Y/%m/%d'),
        ),
    ]
