# Generated by Django 2.2.7 on 2020-06-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20200623_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulacion',
            name='ruta_imagen',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
