# Generated by Django 2.2.7 on 2020-06-23 19:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20200623_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulacion',
            name='fecha_publicacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
    ]
