# Generated by Django 2.2.7 on 2020-06-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20200623_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulacion',
            name='ruta_imagen',
            field=models.FileField(blank=True, null=True, upload_to='simulaciones/'),
        ),
    ]
