# Generated by Django 2.2.7 on 2020-06-23 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20200623_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulacion',
            name='Resultado',
        ),
        migrations.AlterField(
            model_name='simulacion',
            name='ruta_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='simulaciones'),
        ),
    ]
