# Generated by Django 2.2.7 on 2020-06-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20200623_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulacion',
            name='ruta_imagen',
            field=models.FilePathField(default='static/images/fig.png'),
        ),
    ]
